Added initial front end with Next JS
growcenter/next-community pull request #1
Opened 2024-05-13 19:58 UTC by tobiasagyasta

- Added initial front end folder for the project.
- Added a nav bar that navigates to different pages. Content is placeholder for now.

2024-05-14 03:02 UTC, jeremygprawira commented
@tobiasagyasta bukannya si repo ini harusnya gausa pake folder front-end lagi ya? lgsg luarannya tu si next-community ini

2024-05-14 03:02 UTC, jeremygprawira requested changes

2024-05-14 03:02 UTC, jeremygprawira commented on README.md
>  GROW Community Church's Web Application
Harusnya di readme si gaperlu ada semacam changelog gitu ya, jatohnya beda file si, si changelog ini
Readme klo mau pake templatenya juga bole kok

2024-05-14 03:02 UTC, jeremygprawira commented on README.md
>  GROW Community Church's Web Application
Better ganti nama mungkin jd changelog.md

2024-05-14 04:24 UTC, tobiasagyasta commented on README.md
>  GROW Community Church's Web Application
Oke siap, nanti diganti. Tadi gw pakai readme soalnya biar langsung keliatan pas buka repo hehehe

2024-05-14 04:28 UTC, tobiasagyasta commented
> @tobiasagyasta bukannya si repo ini harusnya gausa pake folder front-end lagi ya? lgsg luarannya tu si next-community ini

Ohh karena yang gw tau kan back endnya kan dipisah ya nanti yang pakai Golang dan Postgre? Gw mikirnya mendingan dipisah jadi front end dan back endnya sehingga nggak rumit nantinya pas udah besar reponya. Bagaimana? 

@jeremygprawira @thaddeuscleo

2024-05-15 16:06 UTC, thaddeuscleo requested changes
Malam kak @tobiasagyasta, dari aku mungkin kita rapihin dlu directorynya sama kita start standarisasi komponen pakai Shadcn/ui gmn @jeremygprawira ?

2024-05-15 16:17 UTC, thaddeuscleo commented
Sama mungkin kita bisa pakai standarisasi message commit pakai [git semantic](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716). 

Biar ketika release kita bisa documentasikan seperti beberapa project ini:
- [Dify](https://github.com/langgenius/dify/releases)
- [DevPod](https://github.com/loft-sh/devpod/releases/tag/v0.5.6)
- [Robin](https://github.com/sparckles/Robyn/releases/tag/v0.54.2)

2024-05-16 02:39 UTC, jeremygprawira commented
Setuju buat both shadcn dan git semantic
Tapi pen tambahin, karna kita pake JIRA juga jadi better kyk gini
`feat: GCA-1 | initialize repo next-community`

How? @thaddeuscleo @tobiasagyasta

2024-05-16 02:50 UTC, tobiasagyasta commented
Oke, saya juga setuju. Jadi repo ini akan buat front endnya saja ya?

2024-05-16 03:39 UTC, jeremygprawira commented
Gass biar gapusinggggg

2024-05-16 08:32 UTC, thaddeuscleo commented
Gua setuju juga untuk formating seperti itu @jeremygprawira. mantaps untuk tracking 🤘🏽

2024-06-06 03:59 UTC, tobiasagyasta commented
Halo semua, gw sudah update agar project repo sudah di root. Beberapa dependencies juga sudah gw masukin :
- shadcn ui 
- react-icons
- prisma orm
- next auth and prisma adapter

2024-06-06 05:23 UTC, tobiasagyasta commented
Screenshot for initialized web app :


![screenshot](https://github.com/growcenter/next-community/assets/95297961/76607ddf-46c3-4697-9bba-40462e5cb056)

![screenshot2](https://github.com/growcenter/next-community/assets/95297961/39130932-6d8c-43ac-8178-dd536c5c6371)

Mostly just initial header with shadcn navigation component and some hero text.

2024-06-06 14:18 UTC, jeremygprawira approved these changes

2024-06-06 15:52 UTC, merged